Add github_repository_sbom table
turbot/steampipe-plugin-github pull request #353
Opened 2023-10-21 13:11 UTC by lwakefield

# Example query results
<details>
  <summary>Results</summary>
  
```
> select
  name,
  version,
  license
from
  github_repository_sbom
where
  repository_full_name = 'turbot/steampipe'
limit 10;
+-------------------------------------------------+---------+---------+
| name                                            | version | license |
+-------------------------------------------------+---------+---------+
| npm:@octokit/endpoint                           | 6.0.9   | MIT     |
| npm:@babel/helper-explode-assignable-expression | 7.12.13 | MIT     |
| npm:@babel/helper-environment-visitor           | 7.16.7  | MIT     |
| npm:@babel/helper-hoist-variables               | 7.13.0  | MIT     |
| npm:@babel/compat-data                          | 7.13.12 | MIT     |
| npm:@babel/helper-explode-assignable-expression | 7.16.0  | MIT     |
| npm:@babel/helper-create-class-features-plugin  | 7.12.13 | MIT     |
| npm:tunnel                                      | 0.0.6   | MIT     |
| npm:@babel/compat-data                          | 7.16.4  | MIT     |
| npm:@babel/helper-create-class-features-plugin  | 7.13.11 | MIT     |
+-------------------------------------------------+---------+---------+
```
</details>

First time contributor! I'm looking for / expecting feedback on:
1. Is this the right way to model the data since it is focusing on the packages and not top level SBOM metadata? I can see a possibility where it might be preferred to move this to a `github_repository_sbom_packages` table instead, but unsure if that is the right move or not.
2. Pending 2 - there are some fields missing, I wanted to get feedback before adding them!

2023-10-23 13:29 UTC, cbruno10 commented
Hey @lwakefield , thanks for opening this PR!

I had a look at the [SBOM API](https://docs.github.com/en/free-pro-team@latest/rest/dependency-graph/sboms?apiVersion=2022-11-28), and I think including top level SBOM data is OK and having the `packages` in its own column. So there will be additional columns like `spdx_id` ,`spdx_version`, `creation_info`, `name`, data_license`, etc., along with `packages`, which is a JSONB column.

To make querying easier in examples, you can include an example like:
```sql
select
  s.name as spdx_name,
  p.name as package_name,
  p.version as package_version,
  p.license as package_license
from
  github_repository_sbom as s,
  jsonb_array_elements(packages) as p
where
  repository_full_name = 'turbot/steampipe';
```

Also, I did have a quick look at if this was possible in GitHub's GraphQL API, and it seems like right now it's only in [preview mode](https://docs.github.com/en/graphql/overview/schema-previews#access-to-a-repositorys-dependency-graph-preview), which means it's also subject to API changes, so I think implementing this with the v3 REST API right now makes sense, and we can look at migrating to the GraphQL API when it's more widely available.

2023-10-23 21:16 UTC, lwakefield commented
Thanks @cbruno10 - I pivoted based on your feedback!

2023-10-24 14:30 UTC, cbruno10 requested changes
@lwakefield Thanks for making the quick pivot!

I've left a few additional suggestions, can you please have a look?

2023-10-24 14:30 UTC, cbruno10 commented on github/table_github_repository_sbom.go
> +				Transform:   transform.FromField("DocumentDescribes"),
Do we need the transform for this column (and others)? Usually we only need these when the default transformation (https://github.com/turbot/steampipe-plugin-github/blob/main/github/plugin.go#L18) fails, usually when there's a field name with acronyms, e.g., `SPDXID`. I think we may only need these explicit transforms for the `spdx_id` and maybe the `spdx_version` columns.

2023-10-24 14:30 UTC, cbruno10 commented on github/table_github_repository_sbom.go
> +				Type:        proto.ColumnType_STRING,
For this column, do we get get always a single string, or can we get back a list? Looking at https://docs.github.com/en/rest/dependency-graph/sboms?apiVersion=2022-11-28, the examples show the data as lists.

2023-10-24 14:30 UTC, cbruno10 commented on github/table_github_repository_sbom.go
> +				Description: "The version of the SPDX specification that this document conforms to.",
I think this was a copy and paste error from above

2023-10-24 14:30 UTC, cbruno10 commented on github/table_github_repository_sbom.go
> +				Description: "Array of packages in spdx format.",
```suggestion
				Description: "Array of packages in SPDX format.",
```

2023-10-24 14:30 UTC, cbruno10 commented on github/table_github_repository_sbom.go
> +		Description: "SBOM from a repository.",
```suggestion
		Description: "Get the software bill of materials (SBOM) for a repository.",
```

Description partially taken from https://docs.github.com/en/rest/dependency-graph/sboms?apiVersion=2022-11-28.

2023-10-24 14:30 UTC, cbruno10 commented on docs/tables/github_repository_sbom.md
> +  github_repository_sbom,
Does this example work? I don't think having the table name in the `select` statement would yield anything.

I'd suggest adding some basic SBOM columns like `spdx_id` and `spdx_version` instead.

2023-10-24 14:30 UTC, cbruno10 commented on docs/tables/github_repository_sbom.md
> +## Examples
Are there any other examples you'd want to include based on how you'd use the table to view SBOM/package information? For instance, is there anything in `packages` you'd want to validate specifically?

2023-10-24 14:30 UTC, cbruno10 commented on github/table_github_repository_sbom.go
> +func tableGitHubRepositorySbom() *plugin.Table {
Can you please post what `select * from github_repository_sbom` produces?

2023-10-24 14:30 UTC, cbruno10 commented on docs/tables/github_repository_sbom.md
> +  p->>'licenseConcluded' as package_license
```suggestion
  p ->> 'name' as package_name,
  p ->> 'versionInfo' as package_version,
  p ->> 'licenseConcluded' as package_license
```

2023-11-17 11:58 UTC, madhushreeray30 commented
Re-raised as new PR

2023-11-17 12:31 UTC, merged